package com.experis.de.MeFit.models;

import com.fasterxml.jackson.annotation.JsonGetter;
//import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Entity
@Table(name = "Exercise")
@Schema(description = "Exercise Model")
public  @Getter
        @Setter
        @RequiredArgsConstructor
        class Exercise {

    //autogenerated ID which never has to be defined in future functions.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model
    @Column(name="name",
            nullable = false,
            columnDefinition = "TEXT")
    private String name;

    @Column(name="description",
            nullable = false,
            columnDefinition = "TEXT")
    private String description;

    //related data
    //workout - exercise - relation
    @ManyToOne(cascade = {/*CascadeType.ALL, */CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    @JoinColumn(name="workout_id")
    private Workout workout;

    //restricts the output to the workout ID
    @JsonGetter("workout")
    public String workout() {
        if(workout != null){
            return "/api/v1/workout/" + workout.getId();
        }else{
            return null;
        }
    }

    //related data
    //exercise - muscleGroup - relation
    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    @JoinTable(
            name="exercise_muscleGroups",
            joinColumns = {@JoinColumn(name="exercise_id")},
            inverseJoinColumns = {@JoinColumn(name="muscleGroup_id")}
    )
    private Set<MuscleGroup> muscleGroups = new HashSet<>();

    // restricts the output to a List of IDs of the muscleGroups
    @JsonGetter("muscleGroups")
    public List<String> muscleGroupsGetter() {
        if(muscleGroups != null) {
            return muscleGroups.stream()
                    .map(muscleGroup -> {
                        return "/api/v1/muscleGroups/" + muscleGroup.getId();
                    }).collect(Collectors.toList());
        }
        return null;
    }
}
